### ISSUE TITLE
Support emojis universally 

### ISSUE THREAD

**Issue by adamchainz** [djangolondon/djangolondon.github.io#33]
Use https://github.com/Ranks/emojione to support emojis universally since they don't work if you don't have an emoji compatible font installed

**Comment by jamespacileo** [comment]
Might be wrong, but at first glance it seems the following might be enough

`<script src="//cdn.jsdelivr.net/emojione/2.1.4/lib/js/emojione.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/emojione/2.1.4/assets/css/emojione.min.css"/>`

**Comment by adamchainz** [comment]
PR or didn't happen 📷

**Comment by adamchainz** [comment]
I've tried it (need a little snippet as per [this](http://git.emojione.com/demos/class-convert.html) ) but they come out a bit pixelated since they're up to 64x64 only:

![screen shot 2016-05-11 at 12 57 37](https://cloud.githubusercontent.com/assets/857609/15180367/0e19374c-1779-11e6-9375-c227e20d1163.png)

idk if it's worth it - why can't @seddonym install a fully unicode compatible font? Apparently there's just a package on ubuntu - `ttf-ancient-fonts` - if [this article](http://www.omgubuntu.co.uk/2014/11/see-install-use-emoji-symbols-ubuntu-linux) is still accurate.

**Comment by seddonym** [comment]
I've installed `ttf-ancient-fonts` and the emoticons look a little - well, ancient.  They're good enough for now though, at least next time I can handle things from my own laptop if need be.  Closing.
![screenshot from 2016-05-14 13 51 25](https://cloud.githubusercontent.com/assets/236623/15268548/23686f28-19db-11e6-9664-ec3233e73586.png)
